### ISSUE TITLE
It doesn't work properly

### ISSUE THREAD

**Issue by alexanderNG** [t6nis/moodle-mod_mindmap#5]
I want tio use the mindmap module. But it turned out that he was not working properly. Look at the picture.
![mind
![mindmap](https://cloud.githubusercontent.com/assets/12897395/8163220/44bfcdfc-139b-11e5-93cc-4c5fd0d1cdcc.png)

**Comment by t6nis** [comment]
What Moodle version are you using? Which version of Mindmap?

**Comment by alexanderNG** [comment]
Moodle version  2.8.1.
Module version 
![easycapture2](https://cloud.githubusercontent.com/assets/12897395/8188236/f4b8edd8-146d-11e5-8fc5-0406f976347e.png)
