### ISSUE TITLE
Moodle

### ISSUE THREAD

**Issue by Giulia88** [t6nis/moodle-mod_mindmap#6]
Hello,
in Moodle 3.1.1 I can't use the plugin, I see the message "To add a new node, press the "Insert" key on the keyboard!" but when I click the Ins nothing happens.
Is it compatible with this Moodle version?
THank you

**Comment by t6nis** [comment]
Hello,

I tested this plugin in 3.1.6 and it worked. Try to add a new mindmap module to course and see if that works?

**Comment by Giulia88** [comment]
Hello,

thank you for your reply.

I created a mindmap activity, I inserted the title, description etc…

Follow the screenshot



 

When I click the “Ins” key nothing happens.

 

Thank you in advance.

 

 

 

 

Best regards,

Giulia D'Elia

SmartMedia srl

Via Clitunno, 51 - 00198 Roma

Tel.: +39 06/85301860

Fax: +39 06/62209317

Skype: smartmedia-giulia

 <http://www.smartmediaworld.net/> www.smartmediaworld.net – www.smartnotifyme.com

Social:  <https://www.facebook.com/smartmediaitaly>    <https://twitter.com/smartmediasrl>    <https://www.linkedin.com/company/smartmedia---italy> 

 

 

 

 

Da: Tõnis Tartes [mailto:notifications@github.com] 
Inviato: lunedì 26 giugno 2017 09:15
A: t6nis/moodle-mod_mindmap <moodle-mod_mindmap@noreply.github.com>
Cc: Giulia88 <giulia@smartmediaworld.net>; Author <author@noreply.github.com>
Oggetto: Re: [t6nis/moodle-mod_mindmap] Moodle (#6)

 

Hello,

I tested this plugin in 3.1.6 and it worked. Try to add a new mindmap module to course and see if that works?

**Comment by t6nis** [comment]
New version released. Closing this..
